### ISSUE TITLE
[FEATURE] Add fast CI/CD with GitHub Actions

### ISSUE THREAD

**Issue by evolsb** [evolsb/fast-intercom-mcp#22]
### Goal
Add a lightweight, FAST GitHub Actions workflow that provides basic quality checks without slowing down development.

### Requirements
- **MUST complete in under 2 minutes**
- Run on push to main and on pull requests
- Fail fast on errors
- No heavy dependencies or slow builds

### Implementation Tasks
- [ ] Create `.github/workflows/fast-check.yml`
- [ ] Add Python syntax check (import test)
- [ ] Add ruff linting (configured for speed)
- [ ] Add basic CLI smoke test
- [ ] Configure to run in parallel where possible
- [ ] Add status badge to README

### Proposed Workflow
```yaml
name: Fast Check
on: [push, pull_request]
jobs:
  quick-test:
    runs-on: ubuntu-latest
    timeout-minutes: 2  # Fail if takes too long
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -e . ruff
      - run: python -c "import fast_intercom_mcp"
      - run: ruff check . --select E,F  # Only critical errors
      - run: python -m fast_intercom_mcp --help
```

### What NOT to Include
- ❌ Full test suite runs
- ❌ Coverage reports  
- ❌ Complex dependency installation
- ❌ Docker builds
- ❌ Integration tests
- ❌ Anything that adds more than 30 seconds

### Success Criteria
- Average run time < 90 seconds
- Catches syntax errors and import failures
- Catches critical linting issues
- Provides quick feedback on PRs

### Priority
Medium - This will help catch basic issues early without slowing down the fast development pace.
