### ISSUE TITLE
GitHub Actions Integration Test Workflow - Automated CI/CD Verification

### ISSUE THREAD

**Issue by evolsb** [evolsb/fast-intercom-mcp#37]
## Summary
Create automated GitHub Actions workflow for comprehensive integration testing that runs the same real API tests as the local script in a clean CI/CD environment.

## Related Issues
Part of #35 - Integration Testing Infrastructure & v0.4.0 Release
Builds on #36 - Local Integration Test Script

## Purpose
**Automated verification that expects to pass** - After debugging with local script, this provides clean environment testing with no local interference.

### Workflow Configuration
- **File**: `.github/workflows/integration-test.yml`
- **Triggers**: 
  - Manual dispatch (`workflow_dispatch`)
  - Weekly schedule (Monday 6AM UTC)
  - Pre-release (when version tags are created)
- **Environment**: Ubuntu latest with Python 3.11
- **Timeout**: 30 minutes maximum

### Test Scope (Same as Local)
- **Data Range**: 30+ days of production Intercom conversations
- **Real API**: Connect to production Intercom API
- **Fresh Environment**: Clean Ubuntu container
- **Full Workflow**: Install → Initialize → Sync → Verify → Report

### Secrets Management
- [ ] `INTERCOM_ACCESS_TOKEN` stored in GitHub Secrets
- [ ] Secure handling of API credentials
- [ ] No secrets leaked in logs or artifacts

### Implementation Features
- [ ] Python environment setup and dependency installation
- [ ] Package installation (`pip install -e .`)
- [ ] Integration test execution
- [ ] Performance metrics collection
- [ ] Test result artifacts (logs, performance data)
- [ ] Failure notification and reporting

### Success Criteria
- [ ] Workflow completes successfully in clean environment
- [ ] Same test coverage as local script
- [ ] Performance metrics collected and stored
- [ ] Test artifacts saved for analysis
- [ ] Clear pass/fail reporting

### Workflow Structure
```yaml
name: Integration Test
on:
  workflow_dispatch:
    inputs:
      sync_days:
        description: 'Days of history to sync'
        required: false
        default: '30'
  schedule:
    - cron: '0 6 * * 1'  # Weekly Monday 6AM UTC

jobs:
  integration-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
      - name: Set up Python 3.11
      - name: Install dependencies
      - name: Run integration test
      - name: Collect performance metrics
      - name: Upload test artifacts
```

### Expected Artifacts
- **Test logs**: Complete execution logs
- **Performance metrics**: JSON file with sync speed, response times, memory usage
- **Database snapshot**: Test database for analysis (if test fails)
- **Error reports**: Detailed error information on failures

### Integration with Existing CI
- **Separate from fast-check.yml**: This is comprehensive testing, not quick checks
- **Manual trigger**: Primary usage for verification after changes
- **Scheduled runs**: Weekly confidence checks
- **Pre-release**: Automatic trigger when version tags are created

### Performance Reporting
```
📊 Integration Test Results
✅ Conversations synced: 1,247 (30 days)
✅ Sync speed: 23.4 conv/sec
✅ Average response time: 47ms
✅ Memory usage: 73MB
✅ Database integrity: 100%
⏱️ Total test time: 3m 42s
```

### Error Handling
- [ ] Graceful failure with detailed error messages
- [ ] Test artifacts preserved on failure
- [ ] Clear debugging information
- [ ] No sensitive data in error logs
