### ISSUE TITLE
Docker Clean Install Test - Deployment Verification

### ISSUE THREAD

**Issue by evolsb** [evolsb/fast-intercom-mcp#38]
## Summary
Create Docker-based clean installation test to verify that new users can install and run the fast-intercom-mcp server successfully from scratch.

## Related Issues
Part of #35 - Integration Testing Infrastructure & v0.4.0 Release

## Purpose
**Deployment validation** - Ensure that the installation process works cleanly for new users and that Docker deployment is production-ready.

### Test Scope
- **Fresh Docker Environment**: Clean container with no pre-existing dependencies
- **Full Installation Process**: From git clone to running MCP server
- **Real API Integration**: Connect to production Intercom API
- **Docker Compose**: Test both standalone and compose deployment
- **Clean Uninstall**: Verify complete cleanup

### Implementation Files
- **Test Script**: `scripts/test_docker_install.sh`
- **Docker Test Compose**: `docker-compose.test.yml`
- **Documentation**: Update Docker installation docs

#### Scenario 1: Docker Build from Source
- [x] Fresh Ubuntu container
- [x] Git clone repository
- [x] Docker build from Dockerfile
- [x] Container starts successfully
- [x] Health check passes
- [x] API connection works
- [x] MCP server responds

#### Scenario 2: Docker Compose Deployment
- [x] Fresh environment with Docker Compose
- [x] Use existing `docker-compose.yml`
- [x] Set environment variables
- [x] Services start correctly
- [x] Persistent volumes work
- [x] Network configuration correct
- [x] Logs accessible

#### Scenario 3: Clean Installation Process
- [x] No leftover files or containers
- [x] Environment variables properly handled
- [x] Secrets management works
- [x] Port configuration correct
- [x] Resource limits respected

### Success Criteria
- [x] Docker image builds successfully
- [x] Container starts and passes health checks
- [x] Intercom API connection established
- [x] MCP server accepts connections
- [x] Sync functionality works with real data
- [x] Persistent storage functions correctly
- [x] Clean shutdown and cleanup
- [x] No security vulnerabilities

### Test Implementation
```bash
#\!/bin/bash
# scripts/test_docker_install.sh

set -e

echo "🐳 Testing Docker Clean Install..."

# Test 1: Build from source
echo "📦 Building Docker image from source..."
docker build -t fastintercom-test .

# Test 2: Container startup
echo "🚀 Starting container..."
docker run -d --name fastintercom-test \
  -e INTERCOM_ACCESS_TOKEN="$INTERCOM_ACCESS_TOKEN" \
  -p 8000:8000 \
  fastintercom-test

# Test 3: Health check
echo "🏥 Waiting for health check..."
timeout 60 bash -c 'while [[ "$(docker inspect --format='"'"'{{.State.Health.Status}}'"'"' fastintercom-test)" \!= "healthy" ]]; do sleep 2; done'

# Test 4: API connectivity
echo "🔌 Testing API connectivity..."
docker exec fastintercom-test python -m fast_intercom_mcp.cli status

# Test 5: MCP server response
echo "📡 Testing MCP server..."
curl -f http://localhost:8000/health

# Cleanup
echo "🧹 Cleaning up..."
docker stop fastintercom-test
docker rm fastintercom-test
docker rmi fastintercom-test

echo "✅ Docker clean install test passed\!"
```

### Docker Compose Test
```yaml
# docker-compose.test.yml
version: '3.8'
services:
  fastintercom-test:
    build: .
    environment:
      - INTERCOM_ACCESS_TOKEN=${INTERCOM_ACCESS_TOKEN}
    ports:
      - "8001:8000"  # Different port to avoid conflicts
    volumes:
      - test-data:/data
    healthcheck:
      test: ["CMD", "python", "-m", "fast_intercom_mcp.cli", "status"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  test-data:
```

### Performance Validation
- [x] Container resource usage within limits (512MB memory)
- [x] Startup time acceptable (<60 seconds)
- [x] Health check responds correctly
- [x] Persistent data survives container restart
- [x] Log output properly captured

### Security Verification
- [x] No secrets in container logs
- [x] Proper file permissions
- [x] Non-root user execution
- [x] Network security (only necessary ports exposed)
- [x] Vulnerability scanning passes

### Documentation Updates
- [x] README.md Docker section
- [x] Docker deployment troubleshooting
- [x] Environment variable documentation
- [x] Volume mounting instructions

### Integration with CI/CD
This test can be integrated into GitHub Actions as a separate workflow:
```yaml
name: Docker Install Test
on:
  workflow_dispatch:
  release:
    types: [published]
```

### Expected Output
```
🐳 Docker Clean Install Test Results
✅ Image built successfully (234MB)
✅ Container started in 23s
✅ Health check passed
✅ API connection established
✅ MCP server responding
✅ Data persistence verified
✅ Clean shutdown completed
🎉 Ready for production deployment\!
```
