### ISSUE TITLE
Phase 3: Add comprehensive GitHub Actions workflow

### ISSUE THREAD

**Issue by evolsb** [evolsb/fast-intercom-mcp#68]
## Task
Create GitHub Actions workflow that runs ALL tests before allowing PR merge.

## Requirements
- Run full unit test suite
- Run integration tests with real API
- Run performance benchmarks
- Generate test coverage reports
- Block merge if any critical tests fail

## Implementation Steps
- [x] Create `.github/workflows/integration-check.yml`
- [x] Add matrix testing for Python versions
- [x] Include performance regression checks
- [x] Add test result commenting on PRs
- [x] Configure as required check for merging

## Workflow Structure
```yaml
name: Comprehensive Integration Check
on:
  pull_request:
    types: [opened, synchronize]
  
jobs:
  unit-tests:
    # All unit tests must pass
  
  integration-tests:
    # Real API tests (with test token)
  
  performance-tests:
    # Benchmark against baseline
  
  compatibility-tests:
    # Cross-feature validation
```

## Acceptance Criteria
- Workflow runs on all PRs automatically
- Clear pass/fail status visible
- Detailed logs for debugging
- Performance comparison with main branch
- Required check for PR merge

## Part of
- #61 [EPIC] Complete Testing Infrastructure Overhaul
